// Transaction Types
export const TX_TYPES = {
  L2_CHANGE_PUB_KEY: 8,
  L2_CREATE_SUB_ACCOUNT: 9,
  L2_CREATE_PUBLIC_POOL: 10,
  L2_UPDATE_PUBLIC_POOL: 11,
  L2_TRANSFER: 12,
  L2_WITHDRAW: 13,
  L2_CREATE_ORDER: 14,
  L2_CANCEL_ORDER: 15,
  L2_CANCEL_ALL_ORDERS: 16,
  L2_MODIFY_ORDER: 17,
  L2_MINT_SHARES: 18,
  L2_BURN_SHARES: 19,
  L2_UPDATE_LEVERAGE: 20,
  INTERNAL_CLAIM_ORDER: 21,
  INTERNAL_CANCEL_ORDER: 22,
  INTERNAL_DELEVERAGE: 23,
  INTERNAL_EXIT_POSITION: 24,
  INTERNAL_CANCEL_ALL_ORDERS: 25,
  INTERNAL_LIQUIDATE_POSITION: 26,
  INTERNAL_CREATE_ORDER: 27,
  L2_CREATE_GROUPED_ORDERS: 28,
} as const;

// Order Types
export const ORDER_TYPES = {
  LIMIT_ORDER: 0,
  MARKET_ORDER: 1,
  STOP_LOSS_ORDER: 2,
  STOP_LOSS_LIMIT_ORDER: 3,
  TAKE_PROFIT_ORDER: 4,
  TAKE_PROFIT_LIMIT_ORDER: 5,
  TWAP_ORDER: 6,
  TWAP_SUB_ORDER: 7,
  LIQUIDATION_ORDER: 8,
} as const;

// Order Time-In-Force
export const TIME_IN_FORCE = {
  IMMEDIATE_OR_CANCEL: 0,
  GOOD_TILL_TIME: 1,
  POST_ONLY: 2,
} as const;

// Grouping Types
export const GROUPING_TYPES = {
  GROUPING_TYPE: 0,
  ONE_TRIGGERS_THE_OTHER: 1,
  ONE_CANCELS_THE_OTHER: 2,
  ONE_TRIGGERS_A_ONE_CANCELS_THE_OTHER: 3,
} as const;

// Cancel All Orders Time-In-Force
export const CANCEL_ALL_TIME_IN_FORCE = {
  IMMEDIATE_CANCEL_ALL: 0,
  SCHEDULED_CANCEL_ALL: 1,
  ABORT_SCHEDULED_CANCEL_ALL: 2,
} as const;

// Constants
export const CONSTANTS = {
  HASH_LENGTH: 32,
  ONE_USDC: 1000000,
  FEE_TICK: 1_000_000,
  MARGIN_FRACTION_TICK: 10_000,
  SHARE_TICK: 10_000,
  
  // Account limits
  MIN_ACCOUNT_INDEX: 0,
  MAX_ACCOUNT_INDEX: 281474976710654, // (1 << 48) - 2
  MIN_API_KEY_INDEX: 0,
  MAX_API_KEY_INDEX: 254, // (1 << 8) - 2
  MAX_MASTER_ACCOUNT_INDEX: 140737488355327, // (1 << 47) - 1
  
  // Market limits
  MIN_MARKET_INDEX: 0,
  MAX_MARKET_INDEX: 254, // (1 << 8) - 2
  
  // Pool limits
  MAX_INVESTED_PUBLIC_POOL_COUNT: 16,
  INITIAL_POOL_SHARE_VALUE: 1_000, // 0.001 USDC
  MIN_INITIAL_TOTAL_SHARES: 1_000 * (1000000 / 1_000), // 1,000 USDC worth of shares
  MAX_INITIAL_TOTAL_SHARES: 1_000_000_000 * (1000000 / 1_000), // 1,000,000,000 USDC worth of shares
  MAX_POOL_SHARES: (1 << 60) - 1,
  MAX_BURNT_SHARE_USDC_VALUE: (1 << 60) - 1,
  MAX_POOL_ENTRY_USDC: (1 << 56) - 1, // 2^56 - 1 max USDC to invest in a pool
  MIN_POOL_SHARES_TO_MINT_OR_BURN: 1,
  MAX_POOL_SHARES_TO_MINT_OR_BURN: (1 << 60) - 1,
  
  // Nonce limits
  MIN_NONCE: 0,
  MIN_ORDER_NONCE: 0,
  MAX_ORDER_NONCE: (1 << 48) - 1,
  
  // Order limits
  NIL_CLIENT_ORDER_INDEX: 0,
  NIL_ORDER_INDEX: 0,
  MIN_CLIENT_ORDER_INDEX: 1,
  MAX_CLIENT_ORDER_INDEX: (1 << 48) - 1,
  MIN_ORDER_INDEX: ((1 << 48) - 1) + 1,
  MAX_ORDER_INDEX: (1 << 56) - 1,
  MIN_ORDER_BASE_AMOUNT: 1,
  MAX_ORDER_BASE_AMOUNT: (1 << 48) - 1,
  NIL_ORDER_BASE_AMOUNT: 0,
  NIL_ORDER_PRICE: 0,
  MIN_ORDER_PRICE: 1,
  MAX_ORDER_PRICE: (1 << 32) - 1,
  MIN_ORDER_CANCEL_ALL_PERIOD: 1000 * 60 * 5, // 5 minutes
  MAX_ORDER_CANCEL_ALL_PERIOD: 1000 * 60 * 60 * 24 * 15, // 15 days
  NIL_ORDER_EXPIRY: 0,
  MIN_ORDER_EXPIRY: 1,
  MAX_ORDER_EXPIRY: Number.MAX_SAFE_INTEGER,
  MIN_ORDER_EXPIRY_PERIOD: 1000 * 60 * 5, // 5 minutes
  MAX_ORDER_EXPIRY_PERIOD: 1000 * 60 * 60 * 24 * 30, // 30 days
  NIL_ORDER_TRIGGER_PRICE: 0,
  MIN_ORDER_TRIGGER_PRICE: 1,
  MAX_ORDER_TRIGGER_PRICE: (1 << 32) - 1,
  MAX_GROUPED_ORDER_COUNT: 3,
  MAX_TIMESTAMP: (1 << 48) - 1,
  
  // Exchange limits
  MAX_EXCHANGE_USDC: (1 << 60) - 1,
  MIN_TRANSFER_AMOUNT: 1,
  MAX_TRANSFER_AMOUNT: (1 << 60) - 1,
  MIN_WITHDRAWAL_AMOUNT: 1,
  MAX_WITHDRAWAL_AMOUNT: (1 << 60) - 1,
} as const;

export const NIL_API_KEY_INDEX = CONSTANTS.MAX_API_KEY_INDEX + 1;